### ISSUE TITLE
License of logos?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql-brand#1]
I would like to post a hex sticker (common in R packages) on prqlr.
Is there a License or Terms of Use posted somewhere for the prql logo? (I think the logos are very cool!)
https://eitsupi.github.io/prqlr/

**Comment by max-sixty** [comment]
We don't have anything official yet, but you're more than welcome to use it for the prqlr sticker. Is that sufficient for the moment?

**Comment by eitsupi** [comment]
It is enough. Thank you for answering so quickly!

**Comment by eitsupi** [comment]
> I would like to post a hex sticker (common in R packages) on prqlr.

It was late, but the work was done. eitsupi/prqlr#67

By the way, it would be very useful to have an image of the logo alone without text.

**Comment by max-sixty** [comment]
Great!



> By the way, it would be very useful to have an image of the logo alone without text.

Added in https://github.com/PRQL/prql-brand/commit/c73248897ec3aadea97122f119280bb87b14934d, let me know if that's sufficient. I didn't make all the formats (and just did it in Apple Preview...)

**Comment by eitsupi** [comment]
Thank you for your quick response to this, this is good enough for me!

However, I think it would be better to keep this issue open as others will want to use the logo as PRQL grows in popularity.

**Comment by max-sixty** [comment]
Good idea — let me add something to the Readme

**Comment by max-sixty** [comment]
Done — https://github.com/PRQL/prql-brand/commit/7bc3133ca13057f842279552f4b2cae7073dc337 — do you think that's sufficient?

**Comment by eitsupi** [comment]
> Done — [7bc3133](https://github.com/PRQL/prql-brand/commit/7bc3133ca13057f842279552f4b2cae7073dc337) — do you think that's sufficient?

Thank you for the immediate support!
This is great as it clarified how we should proceed.
