### ISSUE TITLE
Platform icons

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql-brand#3]
- Apple ([guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/), [template](https://developer.apple.com/design/resources/), [Material icon](https://m3.material.io/styles/icons/designing-icons))
- GNOME ([guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html), [template](https://gitlab.gnome.org/Teams/Design/HIG-app-icons/blob/master/template.svg))
- KDE ([guidelines](https://develop.kde.org/hig/style/icons/colorful/))
- Microsoft Fluent Design ([resources](https://developer.microsoft.com/en-us/fluentui#/resources))

**Comment by max-sixty** [comment]
What would these be used for?

**Comment by vanillajonathan** [comment]
As a resource for developers who want to create PRQL applications to use as app icons in their projects.

**Comment by max-sixty** [comment]
Folding the broader issue into the discussion at https://github.com/PRQL/prql-brand/issues/7#issuecomment-1467066931; we can reopen if we decide to do more here
